#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/slayer/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

setxkbmap -layout us,ru,ua -option "grp:ctrl_shift_toggle,grp_led:scrol l" -variant ",winkeys"

fbxkb &
kmix &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/slayer/.fluxbox/log"
