#!/bin/bash

CARD_NUM=0
MIC_DEV=62

CURRENT_MIC=$(amixer -c${CARD_NUM} cget numid=${MIC_DEV} | tail -n1 | perl -pe 's/^(.*?)\=//')

echo "Current Mic: $CURRENT_MIC"

if [[ "$CURRENT_MIC" == "1" ]]; 
then
      echo "Switched to mic 0."
      amixer -c${CARD_NUM} cset numid=${MIC_DEV} 0
else
      echo "Switched to mic 1."
      amixer -c${CARD_NUM} cset numid=${MIC_DEV} 1
fi
